# Generated by Django 4.2.11 on 2024-04-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BidSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequences', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('bid_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding_systems.bidcategory')),
            ],
        ),
        migrations.AddField(
            model_name='bidcategory',
            name='bid_system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding_systems.bidsystem'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('pass', 'pass'), ('x', 'x'), ('xx', 'xx'), ('1♣', '1♣'), ('1♦', '1♦'), ('1♥', '1♥'), ('1♠', '1♠'), ('1NT', '1NT'), ('2♣', '2♣'), ('2♦', '2♦'), ('2♥', '2♥'), ('2♠', '2♠'), ('2NT', '2NT'), ('3♣', '3♣'), ('3♦', '3♦'), ('3♥', '3♥'), ('3♠', '3♠'), ('3NT', '3NT'), ('4♣', '4♣'), ('4♦', '4♦'), ('4♥', '4♥'), ('4♠', '4♠'), ('4NT', '4NT'), ('5♣', '5♣'), ('5♦', '5♦'), ('5♥', '5♥'), ('5♠', '5♠'), ('5NT', '5NT'), ('6♣', '6♣'), ('6♦', '6♦'), ('6♥', '6♥'), ('6♠', '6♠'), ('6NT', '6NT'), ('7♣', '7♣'), ('7♦', '7♦'), ('7♥', '7♥'), ('7♠', '7♠'), ('7NT', '7NT')], max_length=4)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('forcing_type', models.CharField(blank=True, choices=[('NF', 'NF'), ('F1', 'F1'), ('GF', 'GF'), ('transfer', 'transfer'), ('automatic', 'automatic'), ('to pass', 'to pass'), ('NF', 'NF')], max_length=9)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_alerted', models.BooleanField()),
                ('bid_situation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding_systems.bidsituation')),
            ],
        ),
    ]
