# Generated by Django 4.2.11 on 2024-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidcategory',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidsituation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bidsystem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
