# Generated by Django 4.2.11 on 2024-04-28 22:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0002_alter_bid_name_alter_bidcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bidcategory',
            managers=[
                ('query_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
