# Generated by Django 5.0.4 on 2024-04-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0003_alter_bidcategory_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsystem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
