# Generated by Django 5.0.4 on 2024-04-30 11:11

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0004_bidsystem_is_public'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bid',
            managers=[
                ('query_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bidsituation',
            managers=[
                ('query_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bidsystem',
            managers=[
                ('query_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
