# Generated by Django 4.2.11 on 2024-06-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0005_alter_bid_managers_alter_bidsituation_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bid',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='bidcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='bidsituation',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='bidsystem',
            managers=[
            ],
        ),
    ]
