# Generated by Django 4.2.11 on 2024-06-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0005_alter_bid_managers_alter_bidsituation_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_system_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bidding_systems.bidsystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidsituation',
            name='bid_system_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bidding_systems.bidsystem'),
            preserve_default=False,
        ),
    ]
