# Generated by Django 4.2.11 on 2024-06-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_systems', '0006_bidsituation_bid_system_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidsituation',
            name='bid_system_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_system_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bidding_systems.bidsystem'),
            preserve_default=False,
        ),
    ]
