# Generated by Django 4.2.11 on 2024-06-04 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='posts/')),
                ('n_clubs', models.CharField(blank=True, max_length=30)),
                ('n_diamonds', models.CharField(blank=True, max_length=30)),
                ('n_hearts', models.CharField(blank=True, max_length=30)),
                ('n_spades', models.CharField(blank=True, max_length=30)),
                ('e_clubs', models.CharField(blank=True, max_length=30)),
                ('e_diamonds', models.CharField(blank=True, max_length=30)),
                ('e_hearts', models.CharField(blank=True, max_length=30)),
                ('e_spades', models.CharField(blank=True, max_length=30)),
                ('s_clubs', models.CharField(blank=True, max_length=30)),
                ('s_diamonds', models.CharField(blank=True, max_length=30)),
                ('s_hearts', models.CharField(blank=True, max_length=30)),
                ('s_spades', models.CharField(blank=True, max_length=30)),
                ('w_clubs', models.CharField(blank=True, max_length=30)),
                ('w_diamonds', models.CharField(blank=True, max_length=30)),
                ('w_hearts', models.CharField(blank=True, max_length=30)),
                ('w_spades', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='comments/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
