# Generated by Django 5.0.3 on 2024-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_id_accounts_about_you_accounts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
