# Generated by Django 5.0.3 on 2024-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='accounts/static/profile_pics/'),
        ),
    ]
